#!/usr/bin/env perl
use DBI;
use File::Spec;
use File::Slurp;


use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }


unless  (-e "mojo.db") {
print "not found database file .";

}



# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('MyApp');

